### PR TITLE
PR: `PETAL` + `Flutter`

### PR DESCRIPTION
**Pull request by nelsonic**
This PR includes an update to our stack from "PETE" to "PETAL". #87 
It also includes our thoughts on using `Flutter` for cross-platform native apps #81 
My hope is that it answers the question opened by @SimonLab "How to build user interface?" #74
I'm around 80% sure that it's a _really_ good idea to use Flutter and I have already outlined the "pros".
We are _first_ going to build a Web App with the majority of features we want to have.
Once we reach the point where we _need_ a native mobile app, we will go "all in" on `Flutter`. 📱

### CODE REVIEW

**Comment by nelsonic** [comment]
Continue: https://github.com/dwyl/technology-stack/blob/flutter-2020/flutter.md

**Comment by nelsonic** [comment]
[https://insights.stackoverflow.com/survey/2020#technology-most-loved](https://insights.stackoverflow.com/survey/2020#technology-most-loved-dreaded-and-wanted-other-frameworks-libraries-and-tools-loved3)
StackOverflow-survey-2020-flutter-most-loved

**Comment by nelsonic** [comment]
@SimonLab I've tried my best to proof-read this myself. 
Most of the changes are just moving things around. 
The important bit is the update from `PETE` to `PETAL`.
Please review + feedback when you can. (no rush)
Thanks! 🙏

**Comment by nelsonic** [comment]
@SimonLab when you're back from your much deserved family vacation, please review, critique + merge this. Thanks! 🙏

**Review by SimonLab — APPROVED** [review]
Looks good :+1 thanks

**Pull request merged**
